version: "3.8"

services:
    api:
        build:
            context: backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
    web:
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            - "8989:3000"
        expose:
            - 8989
